### ISSUE TITLE
Error about atomicAdd

### ISSUE THREAD

**Issue by jnulzl** [clavichord93/caffe#3]
https://github.com/clavichord93/diagonalwise-refactorization-caffe/blob/219d4f5766c4465b6de7bbddae16178c7adc1cac/src/caffe/util/depthwise_cuda.cu#L193
maybe need change
`atomicAdd(weight_ptr + i * kernel_w + j,data_in_ptr[i * dilation_h * width + j * dilation_w] * val);`
to
`caffe_gpu_atomic_add(data_in_ptr[i * dilation_h * width + j * dilation_w] * val,weight_ptr + i * kernel_w + j);`
and insert header file 
`#include "caffe/util/gpu_util.cuh"`

**Comment by ghost** [comment]
Right. Thanks.
